# -*- coding: utf-8 -*-
"""Graphormer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rCsMFIQUp9d4BUxMOTbrYlHAyEKZcuLW
"""

!pip install torch networkx numpy scikit-learn matplotlib pyvis
!pip install spacy && python -m spacy download en_core_web_sm

import re
import json
import numpy as np
import pandas as pd
from tqdm import tqdm
import networkx as nx
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import torch
import torch.nn as nn
import torch.nn.functional as F

# ----------------------------
# Параметры
# ----------------------------
DF_PATH = "df.tsv"
DFQ_PATH = "dfq.tsv"
TOKEN_WINDOW = 3
EDGE_SIM_THRESHOLD = 0.6
DIST_MAX = 10
GRAPHORMER_D_MODEL = 128
GRAPHORMER_N_HEADS = 4

df = pd.read_csv(DF_PATH, sep="\t", dtype=str)
dfq = pd.read_csv(DFQ_PATH, sep="\t", dtype=str)

print("📘 df (первые строки):")
print(df.head(), "\n")
print("📗 dfq (первые строки):")
print(dfq.head(), "\n")

assert {"aid", "value"}.issubset(df.columns), "df должен иметь колонки aid, value"
assert "user_qu" in dfq.columns, "dfq должен иметь колонку user_qu"

def tokenize(text):
    if not isinstance(text, str): text = ""
    toks = re.findall(r"[A-Za-zА-Яа-яёЁ0-9]+(?:-[A-Za-zА-Яа-яёЁ0-9]+)?", text)
    return [t.lower() for t in toks if len(t) > 0]

token_index, node_to_token, token_occurrences = {}, [], {}
aid_to_token_ids = {}

for _, row in df.iterrows():
    aid, text = row["aid"], row.get("value", "")
    toks = tokenize(text)
    if not toks: continue
    aid_to_token_ids.setdefault(aid, [])
    for t in toks:
        if t not in token_index:
            token_index[t] = len(node_to_token)
            node_to_token.append(t)
            token_occurrences[t] = set()
        token_occurrences[t].add(aid)
        aid_to_token_ids[aid].append(token_index[t])

# добавляем токены вопросов
for q in dfq["user_qu"].astype(str):
    for t in tokenize(q):
        if t not in token_index:
            token_index[t] = len(node_to_token)
            node_to_token.append(t)
            token_occurrences[t] = set()

G = nx.Graph()
G.add_nodes_from(range(len(node_to_token)))
for nid, tok in enumerate(node_to_token):
    G.nodes[nid]["token"] = tok
    G.nodes[nid]["aid_set"] = token_occurrences.get(tok, set())

# co-occurrence edges
print("Строим co-occurrence рёбра...")
for _, row in df.iterrows():
    toks = tokenize(row.get("value", ""))
    node_ids = [token_index[t] for t in toks]
    for i in range(len(node_ids)):
        for j in range(i+1, min(i+1+TOKEN_WINDOW, len(node_ids))):
            u, v = node_ids[i], node_ids[j]
            if u == v: continue
            G.add_edge(u, v, weight=G[u][v]["weight"]+1 if G.has_edge(u, v) else 1.0)

print(f"Узлов: {G.number_of_nodes()} | Рёбер: {G.number_of_edges()}")

print("Кодируем токены через SentenceTransformer...")
sbert = SentenceTransformer("all-MiniLM-L6-v2")
token_embeddings = sbert.encode(node_to_token, show_progress_bar=True, normalize_embeddings=True)

# добавляем similarity-edges между вопросами и токенами
question_tokens = list({t for q in dfq["user_qu"].astype(str) for t in tokenize(q)})
q_token_ids = [token_index[t] for t in question_tokens if t in token_index]

if q_token_ids:
    sim = cosine_similarity(token_embeddings[q_token_ids], token_embeddings)
    for i_q, qnid in enumerate(q_token_ids):
        for j_node, s in enumerate(sim[i_q]):
            if j_node != qnid and s >= EDGE_SIM_THRESHOLD:
                G.add_edge(qnid, j_node, weight=G[qnid][j_node]["weight"]+s if G.has_edge(qnid, j_node) else s)

print(f"После добавления: {G.number_of_edges()} рёбер")

print("Вычисляем матрицу расстояний...")
n = len(G)
dist_mat = np.full((n, n), DIST_MAX, dtype=np.int64)
for i in range(n): dist_mat[i, i] = 0
lengths = dict(nx.all_pairs_shortest_path_length(G, cutoff=DIST_MAX))
for i, d in lengths.items():
    for j, l in d.items():
        dist_mat[i, j] = min(l, DIST_MAX)

# --- Graphormer слои ---
import math

class SimpleGraphormerLayer(nn.Module):
    def __init__(self, d_model, n_heads=4, max_dist=10):
        super().__init__()
        self.n_heads, self.d_head = n_heads, d_model // n_heads
        self.Wq, self.Wk, self.Wv = nn.Linear(d_model, d_model), nn.Linear(d_model, d_model), nn.Linear(d_model, d_model)
        self.out = nn.Linear(d_model, d_model)
        self.dist_emb = nn.Embedding(max_dist+1, n_heads)
        self.norm1, self.norm2 = nn.LayerNorm(d_model), nn.LayerNorm(d_model)
        self.ff = nn.Sequential(nn.Linear(d_model, 4*d_model), nn.ReLU(), nn.Linear(4*d_model, d_model))

    def forward(self, x, dist):
        N = x.size(0)
        Q, K, V = self.Wq(x), self.Wk(x), self.Wv(x)
        Q, K, V = Q.view(N, self.n_heads, -1), K.view(N, self.n_heads, -1), V.view(N, self.n_heads, -1)
        scores = torch.einsum("ihd,jhd->hij", Q, K)/math.sqrt(self.d_head)
        bias = self.dist_emb(torch.clamp(dist, 0, self.dist_emb.num_embeddings-1)).permute(2,0,1)
        att = F.softmax(scores+bias, dim=-1)
        out = torch.einsum("hij,jhd->ihd", att, V).reshape(N, -1)
        x = self.norm1(x + self.out(out))
        return self.norm2(x + self.ff(x))

class SimpleGraphormer(nn.Module):
    def __init__(self, in_dim, d_model=GRAPHORMER_D_MODEL, n_layers=2):
        super().__init__()
        self.proj = nn.Linear(in_dim, d_model)
        self.layers = nn.ModuleList([SimpleGraphormerLayer(d_model) for _ in range(n_layers)])
    def forward(self, x_np, dist_np):
        x = torch.tensor(x_np, dtype=torch.float32)
        dist = torch.tensor(dist_np, dtype=torch.long)
        x = self.proj(x)
        for layer in self.layers: x = layer(x, dist)
        return x.detach().numpy()

model = SimpleGraphormer(token_embeddings.shape[1])
node_repr = model(token_embeddings, dist_mat)

# mean-pool по aid
aid_list = list(aid_to_token_ids)
article_reprs = np.zeros((len(aid_list), node_repr.shape[1]))
for i, aid in enumerate(aid_list):
    ids = aid_to_token_ids[aid]
    article_reprs[i] = node_repr[ids].mean(axis=0) if ids else np.zeros(node_repr.shape[1])
aid_to_repr = {aid_list[i]: article_reprs[i] for i in range(len(aid_list))}

print("Ищем ответы...")
predicted = []
for _, row in tqdm(dfq.iterrows(), total=len(dfq)):
    q_toks = tokenize(str(row["user_qu"]))
    ids = [token_index[t] for t in q_toks if t in token_index]
    q_vec = node_repr[ids].mean(axis=0) if ids else np.zeros(node_repr.shape[1])
    sims = cosine_similarity(q_vec.reshape(1, -1), article_reprs)[0]
    predicted.append(aid_list[int(np.argmax(sims))])

dfq["predicted_aid"] = predicted
if "aid" in dfq:
    acc = (dfq["predicted_aid"].astype(str) == dfq["aid"].astype(str)).mean()
    print(f"✅ Accuracy: {acc:.3f}")
dfq.to_csv("dfq_with_predictions.tsv", sep="\t", index=False)

from pyvis.network import Network
from IPython.display import IFrame

print("Создаём упрощённый HTML-граф (только 20 узлов и рёбра между ними)...")

# создаём подграф с 20 узлами
limited_nodes = list(G.nodes())[:20]
G_sub = G.subgraph(limited_nodes)

# создаём визуализацию
net = Network(height="750px", width="100%", bgcolor="#ffffff", font_color="black",
              notebook=True, cdn_resources="in_line")

# добавляем узлы
for i, tok in enumerate(G_sub.nodes()):
    net.add_node(int(i), label=str(tok))

# добавляем рёбра
for u, v in G_sub.edges():
    net.add_edge(int(limited_nodes.index(u)), int(limited_nodes.index(v)))

# вывод статистики
print(f"Граф содержит {G_sub.number_of_nodes()} узлов и {G_sub.number_of_edges()} рёбер.")

# сохраняем в HTML
html_path = "word_graph_simple.html"
net.write_html(html_path, notebook=False)
print(f"✅ Упрощённый граф сохранён: {html_path}")

print(f"Граф содержит {G.number_of_nodes()} узлов и {G.number_of_edges()} рёбер.")

# =====================================
# 📊 Финальный вывод результатов поиска + Top-1 и Top-3 Accuracy
# =====================================
from sklearn.metrics.pairwise import cosine_similarity
import textwrap

print("\n" + "="*80)
print("📘 РЕЗУЛЬТАТЫ ПОИСКА ОТВЕТОВ (с оценками и метриками)")
print("="*80 + "\n")

TOP_N = 3
SNIPPET_LEN = 100

# Проверяем, что embeddings есть
if 'article_reprs' not in locals():
    article_reprs = enriched_articles
if 'query_reprs' not in locals():
    query_reprs = enriched_questions

top1_correct = 0
top3_correct = 0
total = len(dfq)

for idx, row in enumerate(dfq.itertuples(), 1):
    q = getattr(row, "user_qu", "")
    true_aid = str(getattr(row, "aid", "")) if "aid" in dfq.columns else None

    # Вектор вопроса и косинусная схожесть со статьями
    q_vec = query_reprs[idx-1]
    sims = cosine_similarity(q_vec.reshape(1, -1), article_reprs)[0]
    top_idx = np.argsort(sims)[-TOP_N:][::-1]

    print(f"🔹 Вопрос: {q}")
    print(f"{'-'*90}")

    # Выводим top-3 статьи с оценками
    for rank, i in enumerate(top_idx, 1):
        aid = str(aid_list[i])
        score = sims[i]
        snippet = df[df["aid"] == aid]["value"].astype(str).iloc[0][:SNIPPET_LEN]
        print(f"#{rank}: AID={aid} | SCORE={score:.3f} | {snippet}...")

    # Ожидаемая статья
    if true_aid and true_aid in df["aid"].astype(str).values:
        true_text = df[df["aid"] == true_aid]["value"].astype(str).iloc[0][:SNIPPET_LEN]
        print(f"\n✅ Ожидаемая статья: AID={true_aid} | {true_text}...")
    else:
        print("\n⚠️ Ожидаемая статья отсутствует в df")

    # Проверяем точность
    predicted_top = [str(aid_list[i]) for i in top_idx]
    if len(predicted_top) > 0 and predicted_top[0] == true_aid:
        top1_correct += 1
    if true_aid in predicted_top:
        top3_correct += 1

    print("\n" + "-"*90 + "\n")

# Метрики
acc1 = top1_correct / total if total > 0 else 0
acc3 = top3_correct / total if total > 0 else 0
print(f"🎯 Top-1 Accuracy: {acc1:.3f} ({top1_correct}/{total})")
print(f"🎯 Top-3 Accuracy: {acc3:.3f} ({top3_correct}/{total})")

