# -*- coding: utf-8 -*-
"""SyntaticGraph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eIZufaDu__pouX9uBNWfWvcf0uTq4Qaj
"""

# Cell 1: Установка зависимостей (выполнить в Colab один раз)
!pip install -U pip setuptools wheel >/dev/null
!pip install spacy==3.6.0 networkx matplotlib pandas tqdm >/dev/null
!python -m spacy download ru_core_news_lg >/dev/null
!pip install pyvis >/dev/null
print("Установки завершены.")

# Cell 2: Импорт и настройки
import os
import json
from typing import List, Tuple, Dict, Any
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
from tqdm import tqdm
import spacy
from collections import defaultdict
import math
import random
from pyvis.network import Network  # для интерактивной HTML-визуализации

# Путь к входному файлу (df.tsv должен быть в /content/)
INPUT_PATH = "df.tsv"
OUT_DIR = "syntactic_graph_outputs"
os.makedirs(OUT_DIR, exist_ok=True)

# Исключаем служебные части речи и пунктуацию из графа
EXCLUDED_POS = {"ADP", "CCONJ", "SCONJ", "PART", "PUNCT", "SPACE", "SYM", "INTJ"}

# Загружаем большую русскую модель spaCy
nlp = spacy.load("ru_core_news_lg")

# Увеличиваем лимит длины текста для обработки больших документов
nlp.max_length = 2_000_000

print("spaCy model loaded:", nlp.pipe_names)

# Cell 3: Функции для парсинга, генерации id и построения графа
def parse_sentence_spacy(text: str):
    """
    Возвращает tokens и deps для одного предложения:
    tokens: list of {idx (1-based), surface, lemma, pos}
    deps: list of {head, dep, label}
    Исключает служебные слова (предлоги, союзы, частицы, пунктуацию и т.д.).
    """
    doc = nlp(text)
    tokens = []
    deps = []

    # Сначала строим таблицу индексов, исключая ненужные токены
    filtered = [tok for tok in doc if tok.pos_ not in EXCLUDED_POS]
    old_to_new = {tok.i: i + 1 for i, tok in enumerate(filtered)}  # spaCy idx -> 1-based новый индекс

    for i, tok in enumerate(filtered):
        tokens.append({
            "idx": i + 1,
            "surface": tok.text,
            "lemma": tok.lemma_,
            "pos": tok.pos_
        })

        # Добавляем зависимость, если головное слово не исключено
        if tok.head.i in old_to_new:
            head_idx = old_to_new[tok.head.i]
        else:
            head_idx = 0  # если голова — служебное слово или root

        deps.append({
            "head": head_idx,
            "dep": i + 1,
            "label": tok.dep_
        })

    return tokens, deps

def clean_graph_remove_stopwords(G, nlp_model):
    """
    Удаляет из графа узлы-слова, соответствующие стоп-словам,
    служебным POS и неалфавитным токенам.
    Возвращает новый очищенный граф.
    """
    stop_pos = {"ADP", "CCONJ", "SCONJ", "PART", "PUNCT", "SYM"}
    stops = set(nlp_model.Defaults.stop_words)
    nodes_to_remove = []

    for n, data in G.nodes(data=True):
        if data.get("type") == "instance":
            lemma = str(data.get("lemma", "")).lower()
            pos = data.get("pos", "")
            surface = str(data.get("surface", "")).lower()
            if lemma in stops or pos in stop_pos or not surface.isalpha():
                nodes_to_remove.append(n)

    print(f"Удаляем {len(nodes_to_remove)} служебных/стоп-узлов из {G.number_of_nodes()}")
    G_clean = G.copy()
    G_clean.remove_nodes_from(nodes_to_remove)
    return G_clean



def lemma_node_id(lemma: str, pos: str) -> str:
    """ID узла леммы (общего узла по словоформам)"""
    return f"LEM::{lemma}::{pos}"


def instance_node_id(article_id: str, row_id: Any, sent_id: str, idx: int, surface: str) -> str:
    """ID узла конкретного вхождения слова в тексте"""
    safe = surface.replace(" ", "_")[:40]
    return f"INST::{article_id}::{row_id}::{sent_id}::{idx}::{safe}"


def sentence_node_id(article_id: str, sent_id: str) -> str:
    """ID узла предложения"""
    return f"SENT::{article_id}::{sent_id}"


def safe_str_for_graph(v):
    """Приводит сложные структуры к сериализуемым строкам (для GraphML/GEXF)"""
    if isinstance(v, (list, dict, set)):
        return json.dumps(list(v) if isinstance(v, set) else v, ensure_ascii=False)
    return v

def compute_lemma_idf(G):
    lemma_to_articles = defaultdict(set)
    for n, d in G.nodes(data=True):
        if d.get("type") == "lemma":
            # собираем все статьи для леммы
            for u, v, data in G.in_edges(n, data=True):
                if data.get("type") == "instance_of":
                    aid = G.nodes[u].get("article_id")
                    if aid:
                        lemma_to_articles[d["lemma"]].add(aid)
    N = len({d.get("article_id") for n, d in G.nodes(data=True) if d.get("type") == "instance"})
    idf = {}
    for lemma, arts in lemma_to_articles.items():
        df = len(arts)
        idf[lemma] = math.log((N + 1) / (df + 1))
    return idf

def compute_lemma_pmi(G):
    # Подсчёт частот
    cooccur = defaultdict(int)
    lemma_freq = defaultdict(int)
    total_pairs = 0

    for u, v, data in G.edges(data=True):
        if data.get("type") == "lemma_dep":
            lu, lv = G.nodes[u].get("lemma"), G.nodes[v].get("lemma")
            if lu and lv:
                cooccur[(lu, lv)] += 1
                lemma_freq[lu] += 1
                lemma_freq[lv] += 1
                total_pairs += 1

    # Если нет пар — вернём пустой словарь
    if total_pairs == 0:
        return {}

    # PMI и нормализация в диапазон [0.5, 1.5]
    raw_pmi = {}
    min_pmi = float("inf")
    max_pmi = float("-inf")
    for (lu, lv), c in cooccur.items():
        p_uv = c / total_pairs
        p_u = max(1e-9, lemma_freq[lu] / total_pairs)
        p_v = max(1e-9, lemma_freq[lv] / total_pairs)
        val = math.log((p_uv / (p_u * p_v)) + 1e-9)
        raw_pmi[(lu, lv)] = val
        min_pmi = min(min_pmi, val)
        max_pmi = max(max_pmi, val)

    # Если все PMI одинаковы — вернуть базовый вес 1.0
    pmi_norm = {}
    if max_pmi - min_pmi < 1e-9:
        for k in raw_pmi:
            pmi_norm[k] = 1.0
        return pmi_norm

    # Min-max -> scale to [0.6, 1.4] (вместо [0.5,1.5], немного осторожнее)
    low, high = 0.6, 1.4
    for k, v in raw_pmi.items():
        pmi_norm[k] = low + (v - min_pmi) * (high - low) / (max_pmi - min_pmi)
    return pmi_norm

# Cell 4: Основная функция построения мультиграфа из DataFrame
def build_syntactic_multigraph(df: pd.DataFrame,
                               type_col: str = "type",
                               value_col: str = "value",
                               article_col: str = "aid",
                               use_parsing_fn = parse_sentence_spacy):
    """
    Строит networkx.MultiDiGraph по выбранным строкам df.
    Возвращает (G, lemma_agg) где lemma_agg — агрегированная статистика меж-леммовых зависимостей.

    Изменения:
    - добавлена фильтрация служебных слов (через parse_sentence_spacy)
    - добавлен прогресс и подсчёт токенов
    - улучшена безопасность при добавлении атрибутов (safe_str_for_graph)
    """
    G = nx.MultiDiGraph()
    lemma_agg = {}  # key: (from_lem, to_lem, label) -> {count, doc_set, samples}

    # фильтр строк
    mask = df[type_col].str.lower().isin(["header", "sentence", "question"])
    df_sel = df[mask].copy()
    print("Rows selected for parsing:", len(df_sel))

    for row_idx, row in tqdm(df_sel.iterrows(), total=len(df_sel), desc="Parsing rows"):
        art_id = row.get(article_col, "A_unknown")
        text = row.get(value_col, "")
        if not str(text).strip():
            continue

        sent_unique_id = str(row_idx)

        # parse через нашу функцию, которая уже фильтрует POS
        try:
            tokens, deps = use_parsing_fn(text)
        except Exception as e:
            print(f"⚠️ Parse error at row {row_idx}: {e}")
            continue

        # если после фильтрации нет токенов — пропускаем
        if not tokens:
            continue

        # создаём узел предложения
        # sent_nid = sentence_node_id(art_id, sent_unique_id)
        # if not G.has_node(sent_nid):
        #     G.add_node(
        #         sent_nid,
        #         type="sentence",
        #         article_id=art_id,
        #         sent_id=sent_unique_id,
        #         text=text,
        #     )

        # создаём lemma узлы
        for tok in tokens:
            inst = instance_node_id(art_id, row_idx, sent_unique_id, tok["idx"], tok["surface"])
            lem = lemma_node_id(tok["lemma"], tok["pos"])

            if not G.has_node(inst):
                G.add_node(
                    inst,
                    type="instance",
                    surface=tok["surface"],
                    lemma=tok["lemma"],
                    pos=tok["pos"],
                    article_id=art_id,
                    sent_id=sent_unique_id,
                    tok_index=tok["idx"],
                )

            if not G.has_node(lem):
                G.add_node(
                    lem,
                    type="lemma",
                    lemma=tok["lemma"],
                    pos=tok["pos"],
                    doc_freq=0,
                    token_freq=0,
                )

            # связь instance -> lemma
            G.add_edge(inst, lem, key="instance_of", type="instance_of")

            # обновляем статистику леммы
            G.nodes[lem]["token_freq"] = G.nodes[lem].get("token_freq", 0) + 1
            G.nodes[lem].setdefault("doc_set", set()).add(art_id)

        # словарь токенов по индексам
        inst_by_idx = {
            tok["idx"]: instance_node_id(art_id, row_idx, sent_unique_id, tok["idx"], tok["surface"])
            for tok in tokens
        }

        # связи по синтаксису
        for d in deps:
            head = d["head"]
            dep_idx = d["dep"]
            label = d.get("label", "dep")

            dep_inst = inst_by_idx.get(dep_idx)
            if head == 0:
                # это корень предложения — не связываем с SENT узлом
                head_inst = None
            else:
                head_inst = inst_by_idx.get(head)

            if dep_inst is None or head_inst is None:
                continue


            occ = {
                "article_id": art_id,
                "row_idx": int(row_idx),
                "sent_id": sent_unique_id,
                "head_idx": head,
                "dep_idx": dep_idx,
            }

            G.add_edge(
                head_inst,
                dep_inst,
                key=f"dep::{label}",
                type="dep",
                label=label,
                occurrences=[safe_str_for_graph(occ)],
            )

            # агрегируем лемма-зависимости
            def inst_to_lemma_id(node_id):
                if node_id.startswith("INST::"):
                    for _, v, _, ddata in G.out_edges(node_id, keys=True, data=True):
                        if ddata.get("type") == "instance_of":
                            return v
                return None

            from_lem = inst_to_lemma_id(head_inst)
            to_lem = inst_to_lemma_id(dep_inst)
            if from_lem and to_lem:
                key = (from_lem, to_lem, label)
                rec = lemma_agg.setdefault(key, {"count": 0, "doc_set": set(), "samples": []})
                rec["count"] += 1
                rec["doc_set"].add(art_id)
                if len(rec["samples"]) < 5:
                    rec["samples"].append(occ)

        # соседние связи (по позиции)
        for i in range(len(tokens) - 1):
            id1 = inst_by_idx[tokens[i]["idx"]]
            id2 = inst_by_idx[tokens[i + 1]["idx"]]
            occ = {
                "article_id": art_id,
                "row_idx": int(row_idx),
                "sent_id": sent_unique_id,
                "i": tokens[i]["idx"],
            }
            G.add_edge(id1, id2, key="adj", type="adj", occurrences=[safe_str_for_graph(occ)])

    # финализируем doc_freq
    for n in list(G.nodes):
        if G.nodes[n].get("type") == "lemma":
            doc_set = G.nodes[n].pop("doc_set", set())
            G.nodes[n]["doc_freq"] = len(doc_set)

    # добавляем lemma-level зависимости
    for (from_lem, to_lem, label), meta in lemma_agg.items():
        G.add_edge(
            from_lem,
            to_lem,
            key=f"lemma_dep::{label}",
            type="lemma_dep",
            label=label,
            count=meta["count"],
            doc_freq=len(meta["doc_set"]),
            samples=json.dumps(meta["samples"], ensure_ascii=False),
        )

    return G, lemma_agg

# Cell 5: Загрузка df.tsv и вызов сборки графа
# Если у тебя df.tsv в другом месте, поправь INPUT_PATH в начале
if not os.path.exists(INPUT_PATH):
    # подсказка: можно загрузить файл с локального ПК
    from google.colab import files
    print("Загрузите df.tsv (файл должен содержать колонки: aid, type, value).")
    uploaded = files.upload()
    # сохранение первого файла как df.tsv
    for k in uploaded.keys():
        with open("/content/df.tsv","wb") as f:
            f.write(uploaded[k])
        break

df = pd.read_csv(INPUT_PATH, sep="\t", dtype=str).fillna("")
print("Loaded df shape:", df.shape)
print("Columns:", list(df.columns))

# Укажи имена колонок, если они отличаются
type_col = "type"
value_col = "value"
article_col = "aid"  # если в твоём файле другая колонка — измени здесь

G, lemma_agg = build_syntactic_multigraph(df, type_col=type_col, value_col=value_col, article_col=article_col)
LEMMA_IDF = compute_lemma_idf(G)
LEMMA_PMI = compute_lemma_pmi(G)

G_clean = clean_graph_remove_stopwords(G, nlp)


print("Graph built — nodes:", G.number_of_nodes(), "edges:", G.number_of_edges())

def visualize_graph_html_fixed_draggable(G,
                                         output_html_path="syntactic_graph_fixed_draggable.html",
                                         max_nodes=20,
                                         seed=42):
    """
    Сохраняет интерактивный HTML (pyvis) с фиксированными начальными позициями.
    • Отображает до max_nodes узлов (по степени)
    • Узлы все одного размера
    • Без физики (не двигаются сами)
    • Можно перемещать мышкой (dragNodes=True)
    • Увеличено расстояние между вершинами ×3
    """
    import math
    import networkx as nx
    from pyvis.network import Network

    if G.number_of_nodes() == 0:
        print("Граф пустой — нечего визуализировать.")
        return

    # 1️⃣ Выбираем топ-N по степени
    top_nodes = sorted(G.degree(), key=lambda x: x[1], reverse=True)[:max_nodes]
    chosen_nodes = {n for n, _ in top_nodes}
    subG = G.subgraph(chosen_nodes).copy()
    print(f"Визуализация подграфа: {subG.number_of_nodes()} узлов, {subG.number_of_edges()} рёбер")

    # 2️⃣ Статическая раскладка (spring_layout)
    pos = nx.spring_layout(subG, seed=seed, iterations=300)
    PIXEL_SCALE = 1800.0  # ← было 600.0 (увеличено ×3)
    MIN_DIST = 240.0      # ← было 80.0 (увеличено ×3)
    MAX_ITERS = 200

    # Масштабируем координаты в пиксели
    xs = [p[0] for p in pos.values()]
    ys = [p[1] for p in pos.values()]
    minx, maxx = min(xs), max(xs)
    miny, maxy = min(ys), max(ys)
    width = max(1e-6, maxx - minx)
    height = max(1e-6, maxy - miny)
    pixel_pos = {}
    for n, (x, y) in pos.items():
        nxorm = (x - minx) / width
        nyorm = (y - miny) / height
        px = (nxorm - 0.5) * PIXEL_SCALE
        py = (nyorm - 0.5) * PIXEL_SCALE
        pixel_pos[n] = [px, py]

    # Простое раздвигание близких вершин
    nodes_list = list(pixel_pos.keys())
    for it in range(MAX_ITERS):
        moved = False
        for i in range(len(nodes_list)):
            ni = nodes_list[i]
            xi, yi = pixel_pos[ni]
            for j in range(i + 1, len(nodes_list)):
                nj = nodes_list[j]
                xj, yj = pixel_pos[nj]
                dx = xi - xj
                dy = yi - yj
                dist = math.hypot(dx, dy)
                if dist < MIN_DIST and dist > 0:
                    overlap = (MIN_DIST - dist) / 2.0
                    ux = dx / dist
                    uy = dy / dist
                    pixel_pos[ni][0] += ux * overlap
                    pixel_pos[ni][1] += uy * overlap
                    pixel_pos[nj][0] -= ux * overlap
                    pixel_pos[nj][1] -= uy * overlap
                    moved = True
        if not moved:
            break

    # Центрируем координаты
    all_x = [p[0] for p in pixel_pos.values()]
    all_y = [p[1] for p in pixel_pos.values()]
    mean_x, mean_y = sum(all_x) / len(all_x), sum(all_y) / len(all_y)
    for n in pixel_pos:
        pixel_pos[n][0] -= mean_x
        pixel_pos[n][1] -= mean_y

    # 3️⃣ Создаём pyvis Network
    net = Network(
        directed=True,
        width="100%",
        height="1000px",  # чуть больше, чтобы вместить
        bgcolor="#ffffff",
        font_color="#000000",
        notebook=False
    )

    # 4️⃣ Добавляем узлы — все одного размера, draggable=True
    node_size = 25
    for n, data in subG.nodes(data=True):
        label = data.get("lemma") or data.get("surface") or n.split("::")[-1]
        label = str(label)[:30]
        title = "<br>".join(f"<b>{k}</b>: {v}" for k, v in data.items() if k != "type")
        x, y = pixel_pos[n]
        net.add_node(
            n,
            label=label,
            title=title,
            x=int(x),
            y=int(y),
            size=node_size,
            fixed=False,   # можно двигать
            physics=False, # не двигаются сами
            font={"size": 16}
        )

    # 5️⃣ Добавляем рёбра
    for u, v, data in subG.edges(data=True):
        edge_label = data.get("label") or data.get("type") or ""
        net.add_edge(u, v, label=edge_label, arrows="to", smooth=False)

    # 6️⃣ Настройки визуализации
    net.set_options("""
    var options = {
      "nodes": {
        "font": {"size": 16, "face": "Arial"},
        "borderWidth": 1
      },
      "edges": {
        "color": {"inherit": true},
        "smooth": false
      },
      "interaction": {
        "hover": true,
        "dragNodes": true,
        "zoomView": true
      },
      "physics": {
        "enabled": false
      }
    }
    """)

    net.write_html(output_html_path)
    print(f"HTML-граф сохранён (расстояние ×3): {output_html_path}")

html_path = os.path.join(OUT_DIR, "syntactic_graph_fixed_draggable.html")
visualize_graph_html_fixed_draggable(G_clean, output_html_path=html_path, max_nodes=20)

# === Cell X: Полная информация по слову (лемма или поверхностная форма) ===
def show_full_word_info(word: str, G: nx.MultiDiGraph, lemma_agg: dict):
    """
    Выводит детальную информацию по слову:
      • найденные узлы (instance / lemma)
      • их атрибуты и связи
      • статьи, где встречается лемма
      • агрегированные зависимости из lemma_agg
    """
    word_lower = word.lower()
    matches = [
        n for n, d in G.nodes(data=True)
        if str(d.get("lemma", "")).lower() == word_lower or
           str(d.get("surface", "")).lower() == word_lower
    ]

    if not matches:
        print(f"Слово '{word}' не найдено в графе.")
        return

    print(f"Найдено {len(matches)} узлов для '{word}'.\n")

    lemma_prefix = f"LEM::{word_lower}::"
    total_deps = 0
    docs = set()
    dep_by_label = {}

    # Сбор статистики из lemma_agg
    for (fr, to, lbl), meta in lemma_agg.items():
        if lemma_prefix in fr or lemma_prefix in to:
            total_deps += meta.get("count", 0)
            docs.update(meta.get("doc_set", set()))
            other = to if lemma_prefix in fr else fr
            lemma_other = other.split("::")[1]
            dep_by_label.setdefault(lbl, []).append(lemma_other)

    # Информация по отдельным узлам (первые 5)
    for i, node in enumerate(matches[:5], 1):
        data = G.nodes[node]
        print(f"=== Узел {i}/{min(len(matches), 5)}: {node} ===")
        for k, v in data.items():
            if isinstance(v, (set, list, dict)):
                v = json.dumps(v, ensure_ascii=False)[:200]
            print(f"  {k:12s}: {v}")

        in_edges = list(G.in_edges(node, keys=True, data=True))
        out_edges = list(G.out_edges(node, keys=True, data=True))
        print(f"\nВходящих рёбер: {len(in_edges)}, исходящих: {len(out_edges)}")

        if out_edges:
            print("\nИсходящие связи (до 10):")
            for _, v, k, d in out_edges[:10]:
                lbl = d.get("label") or d.get("type", "")
                target = G.nodes[v].get("lemma") or G.nodes[v].get("surface") or v.split("::")[-1]
                print(f"  → {target[:30]} [{lbl}]")

        if in_edges:
            print("\nВходящие связи (до 10):")
            for u, _, k, d in in_edges[:10]:
                lbl = d.get("label") or d.get("type", "")
                src = G.nodes[u].get("lemma") or G.nodes[u].get("surface") or u.split("::")[-1]
                print(f"  ← {src[:30]} [{lbl}]")

        print("\n" + "—" * 70 + "\n")

    # Общая статистика по лемме
    print(f"Лемма: {word}")
    if total_deps == 0:
        print("Нет агрегированных зависимостей (слово встречается только изолированно).")
        return

    print(f"Всего синтаксических зависимостей: {total_deps}")
    print(f"Встречается в статьях: {len(docs)}")
    if docs:
        sample = ", ".join(sorted(docs)[:10])
        extra = " ..." if len(docs) > 10 else ""
        print(f"  Примеры: {sample}{extra}")

    print("\nТипы зависимостей:")
    for lbl, targets in dep_by_label.items():
        uniq = sorted(set(targets))
        sample = ", ".join(uniq[:5])
        extra = " ..." if len(uniq) > 5 else ""
        print(f"  {lbl:12s} → {len(uniq)} лемм: {sample}{extra}")


# Пример использования
show_full_word_info("семья", G, lemma_agg)

# === Финальные функции поиска с уточняющим вопросом ===

def _get_articles_for_lemma_node(lemma_node: str, G: nx.MultiDiGraph) -> set:
    """Собирает множество article_id из входящих instance_of рёбер (INST → LEM)."""
    articles = set()
    for u, _, data in G.in_edges(lemma_node, data=True):
        if data.get("type") == "instance_of":
            aid = G.nodes[u].get("article_id")
            if aid is not None:
                articles.add(str(aid))
    return articles


def get_most_similar_lemma(word: str, G: nx.MultiDiGraph, nlp_model) -> str | None:
    """
    Ищет лемму в графе с максимальным косинусным сходством по векторам spaCy.
    Возвращает ID узла-леммы, если сходство > 0.55.
    """
    try:
        target_vec = nlp_model(word)
        if target_vec.vector_norm == 0:
            return None
    except Exception:
        return None

    best_sim = -1.0
    best_node = None

    for node, data in G.nodes(data=True):
        if data.get("type") != "lemma":
            continue
        lemma = data.get("lemma", "").strip()
        if not lemma:
            continue
        try:
            sim = nlp_model(lemma).similarity(target_vec)
        except Exception:
            continue
        if sim > best_sim:
            best_sim = sim
            best_node = node

    if best_node and best_sim > 0.55:
        print(f"Похожее слово для «{word}» → «{G.nodes[best_node]['lemma']}» ({best_sim:.2f})")
        return best_node
    return None


def find_best_articles_for_question(question: str,
                                   G: nx.MultiDiGraph,
                                   nlp_model,
                                   normalize=True,
                                   df: pd.DataFrame = None) -> list:
    """
    Основная функция поиска релевантных статей по вопросу:
      • извлекает леммы вопроса
      • точный поиск + fallback по векторному сходству
      • DFS по lemma_dep с учётом пересечения статей
      • возвращает top-3 статей
      • при близких score задаёт уточняющий вопрос
    """
    doc = nlp_model(question)
    lemmas = [tok.lemma_.lower() for tok in doc if tok.pos_ not in EXCLUDED_POS]
    lemmas = list(dict.fromkeys(lemmas))  # сохраняем порядок, убираем дубли

    print(f"\nВопрос: {question}")
    print(f"Леммы вопроса: {lemmas}")

    article_scores: dict[str, float] = {}

    for lemma in lemmas:
        # Точное совпадение
        candidates = [
            n for n, d in G.nodes(data=True)
            if d.get("type") == "lemma" and str(d.get("lemma", "")) == lemma
        ]

        # Похожее слово, если точного нет
        if not candidates:
            sim_node = get_most_similar_lemma(lemma, G, nlp_model)
            if sim_node:
                candidates = [sim_node]

        for node in candidates:
            base_articles = _get_articles_for_lemma_node(node, G)
            if not base_articles:
                continue

            idf = LEMMA_IDF.get(G.nodes[node].get("lemma"), 1.0)
            for aid in base_articles:
                article_scores[aid] = article_scores.get(aid, 0.0) + 2.0 * idf

            # DFS по lemma_dep (без жёсткого ограничения глубины)
            decay_factor = 0.7  # подбирай (0.6-0.85)
            stack = [(node, set(base_articles), 0)]  # (node, articles, depth)
            visited = set()

            max_visited = 5000  # safety limit

            while stack:
                cur_node, cur_articles, depth = stack.pop()
                if cur_node in visited:
                    continue
                visited.add(cur_node)
                if len(visited) > max_visited:
                    break

                for _, neigh, edata in G.out_edges(cur_node, data=True):
                    if edata.get("type") != "lemma_dep":
                        continue

                    lu = G.nodes[cur_node].get("lemma")
                    lv = G.nodes[neigh].get("lemma")
                    pmi_weight = LEMMA_PMI.get((lu, lv), 1.0)

                    neigh_articles = _get_articles_for_lemma_node(neigh, G)
                    if not neigh_articles:
                        continue

                    # Требуем пересечение с текущей веткой
                    if not (neigh_articles & cur_articles):
                        continue

                    merged = neigh_articles | cur_articles
                    # учтём затухание по глубине
                    step_weight = (decay_factor ** depth) * pmi_weight
                    for aid in merged:
                        article_scores[aid] = article_scores.get(aid, 0.0) + 1.0 * step_weight

                    # добавляем с глубиной+1
                    stack.append((neigh, merged, depth + 1))


    # Нормализация по количеству лемм вопроса
    if normalize and lemmas:
        for aid in article_scores:
            article_scores[aid] /= len(lemmas)

    sorted_articles = sorted(article_scores.items(), key=lambda x: x[1], reverse=True)
    top_n = sorted_articles[:3]

    if not top_n:
        print("Не найдено релевантных статей.")
        return []

    print("Топ-кандидаты (aid, score):", top_n)

    # Уточняющий вопрос при близких score
    if len(top_n) >= 2:
        best, second = top_n[0][1], top_n[1][1]
        eps = 1e-9
        if (abs(best - second) / (abs(best) + eps)) < 0.10:
            print("Система не уверена между несколькими статьями — нужен уточняющий вопрос.")

            if df is not None:
                top_ids = [aid for aid, _ in top_n[:2]]
                texts = {}
                for aid in top_ids:
                    rows = df[df["aid"] == aid]["value"].tolist()
                    if rows:
                        texts[aid] = " ".join(rows)

                if len(texts) == 2:
                    aid1, aid2 = list(texts.keys())
                    text1, text2 = texts[aid1], texts[aid2]

                    # Извлечение тематических фраз (ADJ+NOUN или просто NOUN)
                    def extract_phrases(txt):
                        doc_ph = nlp_model(txt)
                        phrases = set()
                        for i, t in enumerate(doc_ph):
                            if t.pos_ == "ADJ" and i + 1 < len(doc_ph) and doc_ph[i + 1].pos_ == "NOUN":
                                phrases.add(f"{t.lemma_.lower()} {doc_ph[i+1].lemma_.lower()}")
                            elif t.pos_ == "NOUN" and len(t.lemma_) > 3:
                                phrases.add(t.lemma_.lower())
                        return phrases

                    ph1, ph2 = extract_phrases(text1), extract_phrases(text2)

                    # Корни тематики
                    roots = {"пособие", "выплата", "ребёнок", "семья", "черновик", "школа", "родство"}
                    common = {r for r in roots if any(r in p for p in ph1) and any(r in p for p in ph2)}

                    # Поиск контрастной пары в общей теме
                    def contrast_pair(p1, p2):
                        best = None
                        best_sim = 0
                        for a in p1:
                            for b in p2:
                                if any(r in a and r in b for r in common):
                                    try:
                                        sim = nlp_model(a).similarity(nlp_model(b))
                                    except Exception:
                                        continue
                                    if 0.2 < sim < 0.7 and sim > best_sim:
                                        best_sim = sim
                                        best = (a, b)
                        return best

                    pair = contrast_pair(ph1, ph2)
                    if pair:
                        a, b = pair
                        print(f"Уточнение: речь о «{a}» или о «{b}»?")
                    else:
                        # fallback на заголовки
                        titles = []
                        for aid in [aid1, aid2]:
                            row = df[df["aid"] == aid]["value"].iloc[0]
                            short = next((r for r in df[df["aid"] == aid]["value"] if len(r.split()) < 10), row)
                            titles.append(short.strip()[:70])
                        print(f"Уточнение: вы имели в виду «{titles[0]}» или «{titles[1]}»?")

    return top_n

from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
DFQ_PATH = "dfq.tsv"
def evaluate_question_search(G: nx.MultiDiGraph,
                             df: pd.DataFrame,
                             nlp_model,
                             dfq_path: str = DFQ_PATH):
    """
    Оценивает качество поиска по тестовому набору dfq.tsv.
    Выводит топ-3 статьи с заголовком и сниппетом.
    Считает Accuracy@1, Accuracy@3, Precision, Recall, F1-score, Loss.
    """
    if not os.path.exists(dfq_path):
        print(f"Файл {dfq_path} не найден.")
        return

    dfq = pd.read_csv(dfq_path, sep="\t", dtype=str).fillna("")
    print(f"Загружено {len(dfq)} тестов из {dfq_path}")
    print("Колонки:", list(dfq.columns))

    # Поиск колонок по алиасам
    q_cols = ["question", "q", "query", "user_qu", "вопрос"]
    exp_cols = ["expected", "true", "aid_true", "aid", "aid_expected", "answer"]

    q_col = next((c for c in dfq.columns if c.lower() in q_cols), None)
    exp_col = next((c for c in dfq.columns if c.lower() in exp_cols), None)

    if not q_col or not exp_col:
        print("Не найдены обязательные колонки (вопрос / ожидаемый aid).")
        return

    print(f"Колонки: question='{q_col}', expected='{exp_col}'")

    df["aid"] = df["aid"].astype(str)
    acc1 = acc3 = total = 0
    y_true = []
    y_pred_top1 = []
    y_pred_top3 = []

    for idx, row in dfq.iterrows():
        question = str(row[q_col]).strip()
        expected = str(row[exp_col]).strip()
        if not question or not expected:
            continue

        print(f"\n=== Тест {idx + 1} ===")
        print(f"Вопрос: {question}")
        print(f"Ожидается: {expected}")

        results = find_best_articles_for_question(
            question, G, nlp_model, df=df, normalize=True
        )

        total += 1
        print("\nТоп-3 найденных статей:")

        found_aids = []
        for rank, (aid, score) in enumerate(results[:3], 1):
            aid_str = str(aid)
            found_aids.append(aid_str)

            rows = df[df["aid"] == aid_str]
            if rows.empty:
                print(f"{rank}. aid={aid_str} | score={score:.3f} → статья отсутствует в df.tsv")
                continue

            text = " ".join(rows["value"].tolist())
            snippet = text[:350] + "…" if len(text) > 350 else text
            header = next((v for v in rows["value"] if len(v.split()) < 12), text.split(".")[0])

            print(f"{rank}. aid={aid_str} | score={score:.3f}")
            print(f"   Заголовок: {header}")
            print(f"   Сниппет: {snippet}\n")

        # === Метрики с учётом равенства скорингов ===
        if found_aids:
            top_score = results[0][1]
            tied_top = [aid for aid, sc in results if abs(sc - top_score) < 1e-9]

            # Accuracy@1
            acc1_flag = int(expected in tied_top)
            acc1 += acc1_flag

            # Accuracy@3
            if len(results) >= 3:
                third_score = results[2][1]
                tied_top3 = [aid for aid, sc in results if sc >= third_score - 1e-9]
                acc3_flag = int(expected in tied_top3)
                acc3 += acc3_flag
            else:
                last_score = results[-1][1]
                tied_topN = [aid for aid, sc in results if sc >= last_score - 1e-9]
                acc3_flag = int(expected in tied_topN)
                acc3 += acc3_flag

            # Сохраняем для метрик
            y_true.append(1)
            y_pred_top1.append(acc1_flag)
            y_pred_top3.append(acc3_flag)

        print("-" * 100)

    # === Итоговые метрики ===
    if total > 0:
        accuracy1 = acc1 / total
        accuracy3 = acc3 / total
        loss = 1 - accuracy1

        precision = precision_score(y_true, y_pred_top1, zero_division=0)
        recall = recall_score(y_true, y_pred_top1, zero_division=0)
        f1 = f1_score(y_true, y_pred_top1, zero_division=0)

        print("\n=== 📊 Итоги ===")
        print(f"Всего тестов: {total}")
        print(f"Accuracy@1: {accuracy1:.3f} ({acc1}/{total})")
        print(f"Accuracy@3: {accuracy3:.3f} ({acc3}/{total})")
        print(f"Loss:       {loss:.3f}")
        print(f"Precision:  {precision:.3f}")
        print(f"Recall:     {recall:.3f}")
        print(f"F1-score:   {f1:.3f}")
    else:
        print("Нет валидных тестов.")

# === Запуск оценки ===
evaluate_question_search(G, df, nlp, DFQ_PATH)

# === Блок: Сохранение исходного графа (все узлы и связи) ===
triplets = []

# Используем исходный граф G (неочищенный)
for u, v, data in G.edges(data=True):
    triplets.append({
        "source": u,
        "target": v,
        "relation": data.get("label") or data.get("type") or "",
        "type": data.get("type", ""),
        "attributes": json.dumps(data, ensure_ascii=False)
    })

# Преобразуем в DataFrame
triplet_df = pd.DataFrame(triplets)

# Сохраняем под именами, явно обозначающими, что это полный граф
csv_path = os.path.join(OUT_DIR, "syntactic_graph_triplets_raw.csv")
tsv_path = os.path.join(OUT_DIR, "syntactic_graph_triplets_raw.tsv")

triplet_df.to_csv(csv_path, index=False, encoding="utf-8")
triplet_df.to_csv(tsv_path, index=False, sep="\t", encoding="utf-8")

print(f"Сохранено {len(triplet_df)} триплетов (исходный граф):")
print(f"  CSV: {csv_path}")
print(f"  TSV: {tsv_path}")